version: '3.7'
services:
    cloud-config:
        image: cloud-config:0.0.1
        ports:
          - "9296:9296"
        restart: always        
        networks:
          - service-compose-network

    naming-server:    
        image: service-registry:0.0.1
        ports:
            - "8761:8761"
        restart: always
        networks:
            - service-compose-network        

networks:
    service-compose-network: