server:
  port: 5000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**
        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/comments/**
        - id: EVEN-BUS-SERVICE
          uri: lb://EVEN-BUS-SERVICE
          predicates:
            - Path=/api/events/**
        - id: QUERY-SERVICE
          uri: lb://QUERY-SERVICE
          predicates:
            - Path=/api/query/**
