version: '3.7'
services:  
    query-service:
        image: query-service:0.0.1
        ports:
            - "4003:4003"
        restart: always        
        networks:
            - service-compose-network

networks:
    service-compose-network: