version: '3.7'
services:  
    query-service:
        container_name: query-service
        image: query-service
        environment:
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
        ports:
            - "4003:4003"
        restart: always        
        networks:
            - service-compose-network

networks:
    service-compose-network: